/* This file was generated by SableCC (http://www.sablecc.org/). */

package cps450.oodle.analysis;

import cps450.oodle.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseTBlank(TBlank node);
    void caseTNewline(TNewline node);
    void caseTBoolean(TBoolean node);
    void caseTBegin(TBegin node);
    void caseTClass(TClass node);
    void caseTElse(TElse node);
    void caseTEnd(TEnd node);
    void caseTFalse(TFalse node);
    void caseTFrom(TFrom node);
    void caseTIf(TIf node);
    void caseTInherits(TInherits node);
    void caseTInt(TInt node);
    void caseTIs(TIs node);
    void caseTLoop(TLoop node);
    void caseTMe(TMe node);
    void caseTNew(TNew node);
    void caseTNull(TNull node);
    void caseTString(TString node);
    void caseTThen(TThen node);
    void caseTTrue(TTrue node);
    void caseTWhile(TWhile node);
    void caseTAnd(TAnd node);
    void caseTOr(TOr node);
    void caseTNot(TNot node);
    void caseTAndOp(TAndOp node);
    void caseTAddOp(TAddOp node);
    void caseTSubOp(TSubOp node);
    void caseTMulOp(TMulOp node);
    void caseTDivOp(TDivOp node);
    void caseTGtOp(TGtOp node);
    void caseTGteqOp(TGteqOp node);
    void caseTEqOp(TEqOp node);
    void caseTAssign(TAssign node);
    void caseTLPar(TLPar node);
    void caseTRPar(TRPar node);
    void caseTLBracket(TLBracket node);
    void caseTRBracket(TRBracket node);
    void caseTComma(TComma node);
    void caseTSemicolon(TSemicolon node);
    void caseTColon(TColon node);
    void caseTPeriod(TPeriod node);
    void caseTComment(TComment node);
    void caseTIdentifier(TIdentifier node);
    void caseTIntLit(TIntLit node);
    void caseTStrLit(TStrLit node);
    void caseTUnterminatedString(TUnterminatedString node);
    void caseTIllegalString(TIllegalString node);
    void caseTEol(TEol node);
    void caseTUnrecognizedChar(TUnrecognizedChar node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
