/* This file was generated by SableCC (http://www.sablecc.org/). */

package cps450.oodle.node;

import cps450.oodle.analysis.*;

@SuppressWarnings("nls")
public final class AAddExpr4 extends PExpr4
{
    private PExpr4 _starts_;
    private TOpPlus _opPlus_;
    private PExpr5 _ends_;

    public AAddExpr4()
    {
        // Constructor
    }

    public AAddExpr4(
        @SuppressWarnings("hiding") PExpr4 _starts_,
        @SuppressWarnings("hiding") TOpPlus _opPlus_,
        @SuppressWarnings("hiding") PExpr5 _ends_)
    {
        // Constructor
        setStarts(_starts_);

        setOpPlus(_opPlus_);

        setEnds(_ends_);

    }

    @Override
    public Object clone()
    {
        return new AAddExpr4(
            cloneNode(this._starts_),
            cloneNode(this._opPlus_),
            cloneNode(this._ends_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAddExpr4(this);
    }

    public PExpr4 getStarts()
    {
        return this._starts_;
    }

    public void setStarts(PExpr4 node)
    {
        if(this._starts_ != null)
        {
            this._starts_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._starts_ = node;
    }

    public TOpPlus getOpPlus()
    {
        return this._opPlus_;
    }

    public void setOpPlus(TOpPlus node)
    {
        if(this._opPlus_ != null)
        {
            this._opPlus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opPlus_ = node;
    }

    public PExpr5 getEnds()
    {
        return this._ends_;
    }

    public void setEnds(PExpr5 node)
    {
        if(this._ends_ != null)
        {
            this._ends_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ends_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._starts_)
            + toString(this._opPlus_)
            + toString(this._ends_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._starts_ == child)
        {
            this._starts_ = null;
            return;
        }

        if(this._opPlus_ == child)
        {
            this._opPlus_ = null;
            return;
        }

        if(this._ends_ == child)
        {
            this._ends_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._starts_ == oldChild)
        {
            setStarts((PExpr4) newChild);
            return;
        }

        if(this._opPlus_ == oldChild)
        {
            setOpPlus((TOpPlus) newChild);
            return;
        }

        if(this._ends_ == oldChild)
        {
            setEnds((PExpr5) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
