/* This file was generated by SableCC (http://www.sablecc.org/). */

package cps450.oodle.node;

import cps450.oodle.analysis.*;

@SuppressWarnings("nls")
public final class AAndExpr1 extends PExpr1
{
    private PExpr1 _starts_;
    private TAnd _and_;
    private PExpr2 _ends_;

    public AAndExpr1()
    {
        // Constructor
    }

    public AAndExpr1(
        @SuppressWarnings("hiding") PExpr1 _starts_,
        @SuppressWarnings("hiding") TAnd _and_,
        @SuppressWarnings("hiding") PExpr2 _ends_)
    {
        // Constructor
        setStarts(_starts_);

        setAnd(_and_);

        setEnds(_ends_);

    }

    @Override
    public Object clone()
    {
        return new AAndExpr1(
            cloneNode(this._starts_),
            cloneNode(this._and_),
            cloneNode(this._ends_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAndExpr1(this);
    }

    public PExpr1 getStarts()
    {
        return this._starts_;
    }

    public void setStarts(PExpr1 node)
    {
        if(this._starts_ != null)
        {
            this._starts_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._starts_ = node;
    }

    public TAnd getAnd()
    {
        return this._and_;
    }

    public void setAnd(TAnd node)
    {
        if(this._and_ != null)
        {
            this._and_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._and_ = node;
    }

    public PExpr2 getEnds()
    {
        return this._ends_;
    }

    public void setEnds(PExpr2 node)
    {
        if(this._ends_ != null)
        {
            this._ends_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ends_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._starts_)
            + toString(this._and_)
            + toString(this._ends_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._starts_ == child)
        {
            this._starts_ = null;
            return;
        }

        if(this._and_ == child)
        {
            this._and_ = null;
            return;
        }

        if(this._ends_ == child)
        {
            this._ends_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._starts_ == oldChild)
        {
            setStarts((PExpr1) newChild);
            return;
        }

        if(this._and_ == oldChild)
        {
            setAnd((TAnd) newChild);
            return;
        }

        if(this._ends_ == oldChild)
        {
            setEnds((PExpr2) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
