/* This file was generated by SableCC (http://www.sablecc.org/). */

package cps450.oodle.node;

import cps450.oodle.analysis.*;

@SuppressWarnings("nls")
public final class AArgDeclTail extends PArgDeclTail
{
    private TSemicolon _semicolon_;
    private PArgDecl _argDecl_;

    public AArgDeclTail()
    {
        // Constructor
    }

    public AArgDeclTail(
        @SuppressWarnings("hiding") TSemicolon _semicolon_,
        @SuppressWarnings("hiding") PArgDecl _argDecl_)
    {
        // Constructor
        setSemicolon(_semicolon_);

        setArgDecl(_argDecl_);

    }

    @Override
    public Object clone()
    {
        return new AArgDeclTail(
            cloneNode(this._semicolon_),
            cloneNode(this._argDecl_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArgDeclTail(this);
    }

    public TSemicolon getSemicolon()
    {
        return this._semicolon_;
    }

    public void setSemicolon(TSemicolon node)
    {
        if(this._semicolon_ != null)
        {
            this._semicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semicolon_ = node;
    }

    public PArgDecl getArgDecl()
    {
        return this._argDecl_;
    }

    public void setArgDecl(PArgDecl node)
    {
        if(this._argDecl_ != null)
        {
            this._argDecl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._argDecl_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._semicolon_)
            + toString(this._argDecl_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._semicolon_ == child)
        {
            this._semicolon_ = null;
            return;
        }

        if(this._argDecl_ == child)
        {
            this._argDecl_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._semicolon_ == oldChild)
        {
            setSemicolon((TSemicolon) newChild);
            return;
        }

        if(this._argDecl_ == oldChild)
        {
            setArgDecl((PArgDecl) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
