/* This file was generated by SableCC (http://www.sablecc.org/). */

package cps450.oodle.node;

import java.util.*;
import cps450.oodle.analysis.*;

@SuppressWarnings("nls")
public final class AArrInxExpr9 extends PExpr9
{
    private TId _quart_;
    private final LinkedList<PPartArrInx> _partArrInx_ = new LinkedList<PPartArrInx>();

    public AArrInxExpr9()
    {
        // Constructor
    }

    public AArrInxExpr9(
        @SuppressWarnings("hiding") TId _quart_,
        @SuppressWarnings("hiding") List<?> _partArrInx_)
    {
        // Constructor
        setQuart(_quart_);

        setPartArrInx(_partArrInx_);

    }

    @Override
    public Object clone()
    {
        return new AArrInxExpr9(
            cloneNode(this._quart_),
            cloneList(this._partArrInx_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArrInxExpr9(this);
    }

    public TId getQuart()
    {
        return this._quart_;
    }

    public void setQuart(TId node)
    {
        if(this._quart_ != null)
        {
            this._quart_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._quart_ = node;
    }

    public LinkedList<PPartArrInx> getPartArrInx()
    {
        return this._partArrInx_;
    }

    public void setPartArrInx(List<?> list)
    {
        for(PPartArrInx e : this._partArrInx_)
        {
            e.parent(null);
        }
        this._partArrInx_.clear();

        for(Object obj_e : list)
        {
            PPartArrInx e = (PPartArrInx) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._partArrInx_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._quart_)
            + toString(this._partArrInx_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._quart_ == child)
        {
            this._quart_ = null;
            return;
        }

        if(this._partArrInx_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._quart_ == oldChild)
        {
            setQuart((TId) newChild);
            return;
        }

        for(ListIterator<PPartArrInx> i = this._partArrInx_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PPartArrInx) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
