/* This file was generated by SableCC (http://www.sablecc.org/). */

package cps450.oodle.node;

import cps450.oodle.analysis.*;

@SuppressWarnings("nls")
public final class AArrType extends PType
{
    private PType _type_;
    private TLBrkt _lBrkt_;
    private PExpr _expr_;
    private TRBrkt _rBrkt_;

    public AArrType()
    {
        // Constructor
    }

    public AArrType(
        @SuppressWarnings("hiding") PType _type_,
        @SuppressWarnings("hiding") TLBrkt _lBrkt_,
        @SuppressWarnings("hiding") PExpr _expr_,
        @SuppressWarnings("hiding") TRBrkt _rBrkt_)
    {
        // Constructor
        setType(_type_);

        setLBrkt(_lBrkt_);

        setExpr(_expr_);

        setRBrkt(_rBrkt_);

    }

    @Override
    public Object clone()
    {
        return new AArrType(
            cloneNode(this._type_),
            cloneNode(this._lBrkt_),
            cloneNode(this._expr_),
            cloneNode(this._rBrkt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArrType(this);
    }

    public PType getType()
    {
        return this._type_;
    }

    public void setType(PType node)
    {
        if(this._type_ != null)
        {
            this._type_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._type_ = node;
    }

    public TLBrkt getLBrkt()
    {
        return this._lBrkt_;
    }

    public void setLBrkt(TLBrkt node)
    {
        if(this._lBrkt_ != null)
        {
            this._lBrkt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lBrkt_ = node;
    }

    public PExpr getExpr()
    {
        return this._expr_;
    }

    public void setExpr(PExpr node)
    {
        if(this._expr_ != null)
        {
            this._expr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr_ = node;
    }

    public TRBrkt getRBrkt()
    {
        return this._rBrkt_;
    }

    public void setRBrkt(TRBrkt node)
    {
        if(this._rBrkt_ != null)
        {
            this._rBrkt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rBrkt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._type_)
            + toString(this._lBrkt_)
            + toString(this._expr_)
            + toString(this._rBrkt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._type_ == child)
        {
            this._type_ = null;
            return;
        }

        if(this._lBrkt_ == child)
        {
            this._lBrkt_ = null;
            return;
        }

        if(this._expr_ == child)
        {
            this._expr_ = null;
            return;
        }

        if(this._rBrkt_ == child)
        {
            this._rBrkt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._type_ == oldChild)
        {
            setType((PType) newChild);
            return;
        }

        if(this._lBrkt_ == oldChild)
        {
            setLBrkt((TLBrkt) newChild);
            return;
        }

        if(this._expr_ == oldChild)
        {
            setExpr((PExpr) newChild);
            return;
        }

        if(this._rBrkt_ == oldChild)
        {
            setRBrkt((TRBrkt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
