/* This file was generated by SableCC (http://www.sablecc.org/). */

package cps450.oodle.node;

import cps450.oodle.analysis.*;

@SuppressWarnings("nls")
public final class ACatExpr3 extends PExpr3
{
    private PExpr3 _starts_;
    private TOpCat _opCat_;
    private PExpr4 _ends_;

    public ACatExpr3()
    {
        // Constructor
    }

    public ACatExpr3(
        @SuppressWarnings("hiding") PExpr3 _starts_,
        @SuppressWarnings("hiding") TOpCat _opCat_,
        @SuppressWarnings("hiding") PExpr4 _ends_)
    {
        // Constructor
        setStarts(_starts_);

        setOpCat(_opCat_);

        setEnds(_ends_);

    }

    @Override
    public Object clone()
    {
        return new ACatExpr3(
            cloneNode(this._starts_),
            cloneNode(this._opCat_),
            cloneNode(this._ends_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACatExpr3(this);
    }

    public PExpr3 getStarts()
    {
        return this._starts_;
    }

    public void setStarts(PExpr3 node)
    {
        if(this._starts_ != null)
        {
            this._starts_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._starts_ = node;
    }

    public TOpCat getOpCat()
    {
        return this._opCat_;
    }

    public void setOpCat(TOpCat node)
    {
        if(this._opCat_ != null)
        {
            this._opCat_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opCat_ = node;
    }

    public PExpr4 getEnds()
    {
        return this._ends_;
    }

    public void setEnds(PExpr4 node)
    {
        if(this._ends_ != null)
        {
            this._ends_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ends_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._starts_)
            + toString(this._opCat_)
            + toString(this._ends_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._starts_ == child)
        {
            this._starts_ = null;
            return;
        }

        if(this._opCat_ == child)
        {
            this._opCat_ = null;
            return;
        }

        if(this._ends_ == child)
        {
            this._ends_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._starts_ == oldChild)
        {
            setStarts((PExpr3) newChild);
            return;
        }

        if(this._opCat_ == oldChild)
        {
            setOpCat((TOpCat) newChild);
            return;
        }

        if(this._ends_ == oldChild)
        {
            setEnds((PExpr4) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
