/* This file was generated by SableCC (http://www.sablecc.org/). */

package cps450.oodle.node;

import cps450.oodle.analysis.*;

@SuppressWarnings("nls")
public final class AClassDefs extends PClassDefs
{
    private PNewlines _newlines_;
    private PClassDef _classDef_;

    public AClassDefs()
    {
        // Constructor
    }

    public AClassDefs(
        @SuppressWarnings("hiding") PNewlines _newlines_,
        @SuppressWarnings("hiding") PClassDef _classDef_)
    {
        // Constructor
        setNewlines(_newlines_);

        setClassDef(_classDef_);

    }

    @Override
    public Object clone()
    {
        return new AClassDefs(
            cloneNode(this._newlines_),
            cloneNode(this._classDef_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAClassDefs(this);
    }

    public PNewlines getNewlines()
    {
        return this._newlines_;
    }

    public void setNewlines(PNewlines node)
    {
        if(this._newlines_ != null)
        {
            this._newlines_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._newlines_ = node;
    }

    public PClassDef getClassDef()
    {
        return this._classDef_;
    }

    public void setClassDef(PClassDef node)
    {
        if(this._classDef_ != null)
        {
            this._classDef_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._classDef_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._newlines_)
            + toString(this._classDef_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._newlines_ == child)
        {
            this._newlines_ = null;
            return;
        }

        if(this._classDef_ == child)
        {
            this._classDef_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._newlines_ == oldChild)
        {
            setNewlines((PNewlines) newChild);
            return;
        }

        if(this._classDef_ == oldChild)
        {
            setClassDef((PClassDef) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
