/* This file was generated by SableCC (http://www.sablecc.org/). */

package cps450.oodle.node;

import java.util.*;
import cps450.oodle.analysis.*;

@SuppressWarnings("nls")
public final class AClassDef extends PClassDef
{
    private TClassId _classId_;
    private TId _stid_;
    private PInheritsFrom _inheritsFrom_;
    private TIs _is_;
    private PNewlines _newlines_;
    private final LinkedList<PVarDecl> _varDecl_ = new LinkedList<PVarDecl>();
    private final LinkedList<PMethodDecl> _methodDecl_ = new LinkedList<PMethodDecl>();
    private TEnd _end_;
    private TId _endid_;

    public AClassDef()
    {
        // Constructor
    }

    public AClassDef(
        @SuppressWarnings("hiding") TClassId _classId_,
        @SuppressWarnings("hiding") TId _stid_,
        @SuppressWarnings("hiding") PInheritsFrom _inheritsFrom_,
        @SuppressWarnings("hiding") TIs _is_,
        @SuppressWarnings("hiding") PNewlines _newlines_,
        @SuppressWarnings("hiding") List<?> _varDecl_,
        @SuppressWarnings("hiding") List<?> _methodDecl_,
        @SuppressWarnings("hiding") TEnd _end_,
        @SuppressWarnings("hiding") TId _endid_)
    {
        // Constructor
        setClassId(_classId_);

        setStid(_stid_);

        setInheritsFrom(_inheritsFrom_);

        setIs(_is_);

        setNewlines(_newlines_);

        setVarDecl(_varDecl_);

        setMethodDecl(_methodDecl_);

        setEnd(_end_);

        setEndid(_endid_);

    }

    @Override
    public Object clone()
    {
        return new AClassDef(
            cloneNode(this._classId_),
            cloneNode(this._stid_),
            cloneNode(this._inheritsFrom_),
            cloneNode(this._is_),
            cloneNode(this._newlines_),
            cloneList(this._varDecl_),
            cloneList(this._methodDecl_),
            cloneNode(this._end_),
            cloneNode(this._endid_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAClassDef(this);
    }

    public TClassId getClassId()
    {
        return this._classId_;
    }

    public void setClassId(TClassId node)
    {
        if(this._classId_ != null)
        {
            this._classId_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._classId_ = node;
    }

    public TId getStid()
    {
        return this._stid_;
    }

    public void setStid(TId node)
    {
        if(this._stid_ != null)
        {
            this._stid_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._stid_ = node;
    }

    public PInheritsFrom getInheritsFrom()
    {
        return this._inheritsFrom_;
    }

    public void setInheritsFrom(PInheritsFrom node)
    {
        if(this._inheritsFrom_ != null)
        {
            this._inheritsFrom_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._inheritsFrom_ = node;
    }

    public TIs getIs()
    {
        return this._is_;
    }

    public void setIs(TIs node)
    {
        if(this._is_ != null)
        {
            this._is_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._is_ = node;
    }

    public PNewlines getNewlines()
    {
        return this._newlines_;
    }

    public void setNewlines(PNewlines node)
    {
        if(this._newlines_ != null)
        {
            this._newlines_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._newlines_ = node;
    }

    public LinkedList<PVarDecl> getVarDecl()
    {
        return this._varDecl_;
    }

    public void setVarDecl(List<?> list)
    {
        for(PVarDecl e : this._varDecl_)
        {
            e.parent(null);
        }
        this._varDecl_.clear();

        for(Object obj_e : list)
        {
            PVarDecl e = (PVarDecl) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._varDecl_.add(e);
        }
    }

    public LinkedList<PMethodDecl> getMethodDecl()
    {
        return this._methodDecl_;
    }

    public void setMethodDecl(List<?> list)
    {
        for(PMethodDecl e : this._methodDecl_)
        {
            e.parent(null);
        }
        this._methodDecl_.clear();

        for(Object obj_e : list)
        {
            PMethodDecl e = (PMethodDecl) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._methodDecl_.add(e);
        }
    }

    public TEnd getEnd()
    {
        return this._end_;
    }

    public void setEnd(TEnd node)
    {
        if(this._end_ != null)
        {
            this._end_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._end_ = node;
    }

    public TId getEndid()
    {
        return this._endid_;
    }

    public void setEndid(TId node)
    {
        if(this._endid_ != null)
        {
            this._endid_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._endid_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._classId_)
            + toString(this._stid_)
            + toString(this._inheritsFrom_)
            + toString(this._is_)
            + toString(this._newlines_)
            + toString(this._varDecl_)
            + toString(this._methodDecl_)
            + toString(this._end_)
            + toString(this._endid_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._classId_ == child)
        {
            this._classId_ = null;
            return;
        }

        if(this._stid_ == child)
        {
            this._stid_ = null;
            return;
        }

        if(this._inheritsFrom_ == child)
        {
            this._inheritsFrom_ = null;
            return;
        }

        if(this._is_ == child)
        {
            this._is_ = null;
            return;
        }

        if(this._newlines_ == child)
        {
            this._newlines_ = null;
            return;
        }

        if(this._varDecl_.remove(child))
        {
            return;
        }

        if(this._methodDecl_.remove(child))
        {
            return;
        }

        if(this._end_ == child)
        {
            this._end_ = null;
            return;
        }

        if(this._endid_ == child)
        {
            this._endid_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._classId_ == oldChild)
        {
            setClassId((TClassId) newChild);
            return;
        }

        if(this._stid_ == oldChild)
        {
            setStid((TId) newChild);
            return;
        }

        if(this._inheritsFrom_ == oldChild)
        {
            setInheritsFrom((PInheritsFrom) newChild);
            return;
        }

        if(this._is_ == oldChild)
        {
            setIs((TIs) newChild);
            return;
        }

        if(this._newlines_ == oldChild)
        {
            setNewlines((PNewlines) newChild);
            return;
        }

        for(ListIterator<PVarDecl> i = this._varDecl_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PVarDecl) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        for(ListIterator<PMethodDecl> i = this._methodDecl_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PMethodDecl) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._end_ == oldChild)
        {
            setEnd((TEnd) newChild);
            return;
        }

        if(this._endid_ == oldChild)
        {
            setEndid((TId) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
