/* This file was generated by SableCC (http://www.sablecc.org/). */

package cps450.oodle.node;

import cps450.oodle.analysis.*;

@SuppressWarnings("nls")
public final class AColonTypeProduction extends PColonTypeProduction
{
    private TColon _colon_;
    private PTypeProduction _typeProduction_;

    public AColonTypeProduction()
    {
        // Constructor
    }

    public AColonTypeProduction(
        @SuppressWarnings("hiding") TColon _colon_,
        @SuppressWarnings("hiding") PTypeProduction _typeProduction_)
    {
        // Constructor
        setColon(_colon_);

        setTypeProduction(_typeProduction_);

    }

    @Override
    public Object clone()
    {
        return new AColonTypeProduction(
            cloneNode(this._colon_),
            cloneNode(this._typeProduction_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAColonTypeProduction(this);
    }

    public TColon getColon()
    {
        return this._colon_;
    }

    public void setColon(TColon node)
    {
        if(this._colon_ != null)
        {
            this._colon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._colon_ = node;
    }

    public PTypeProduction getTypeProduction()
    {
        return this._typeProduction_;
    }

    public void setTypeProduction(PTypeProduction node)
    {
        if(this._typeProduction_ != null)
        {
            this._typeProduction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._typeProduction_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._colon_)
            + toString(this._typeProduction_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._colon_ == child)
        {
            this._colon_ = null;
            return;
        }

        if(this._typeProduction_ == child)
        {
            this._typeProduction_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._colon_ == oldChild)
        {
            setColon((TColon) newChild);
            return;
        }

        if(this._typeProduction_ == oldChild)
        {
            setTypeProduction((PTypeProduction) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
