/* This file was generated by SableCC (http://www.sablecc.org/). */

package cps450.oodle.node;

import cps450.oodle.analysis.*;

@SuppressWarnings("nls")
public final class AEqExpressionLvl4 extends PExpressionLvl4
{
    private PExpressionLvl4 _expressionLvl4_;
    private TEqOp _eqOp_;
    private PExpressionLvl41 _expressionLvl41_;

    public AEqExpressionLvl4()
    {
        // Constructor
    }

    public AEqExpressionLvl4(
        @SuppressWarnings("hiding") PExpressionLvl4 _expressionLvl4_,
        @SuppressWarnings("hiding") TEqOp _eqOp_,
        @SuppressWarnings("hiding") PExpressionLvl41 _expressionLvl41_)
    {
        // Constructor
        setExpressionLvl4(_expressionLvl4_);

        setEqOp(_eqOp_);

        setExpressionLvl41(_expressionLvl41_);

    }

    @Override
    public Object clone()
    {
        return new AEqExpressionLvl4(
            cloneNode(this._expressionLvl4_),
            cloneNode(this._eqOp_),
            cloneNode(this._expressionLvl41_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEqExpressionLvl4(this);
    }

    public PExpressionLvl4 getExpressionLvl4()
    {
        return this._expressionLvl4_;
    }

    public void setExpressionLvl4(PExpressionLvl4 node)
    {
        if(this._expressionLvl4_ != null)
        {
            this._expressionLvl4_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressionLvl4_ = node;
    }

    public TEqOp getEqOp()
    {
        return this._eqOp_;
    }

    public void setEqOp(TEqOp node)
    {
        if(this._eqOp_ != null)
        {
            this._eqOp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._eqOp_ = node;
    }

    public PExpressionLvl41 getExpressionLvl41()
    {
        return this._expressionLvl41_;
    }

    public void setExpressionLvl41(PExpressionLvl41 node)
    {
        if(this._expressionLvl41_ != null)
        {
            this._expressionLvl41_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressionLvl41_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expressionLvl4_)
            + toString(this._eqOp_)
            + toString(this._expressionLvl41_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expressionLvl4_ == child)
        {
            this._expressionLvl4_ = null;
            return;
        }

        if(this._eqOp_ == child)
        {
            this._eqOp_ = null;
            return;
        }

        if(this._expressionLvl41_ == child)
        {
            this._expressionLvl41_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expressionLvl4_ == oldChild)
        {
            setExpressionLvl4((PExpressionLvl4) newChild);
            return;
        }

        if(this._eqOp_ == oldChild)
        {
            setEqOp((TEqOp) newChild);
            return;
        }

        if(this._expressionLvl41_ == oldChild)
        {
            setExpressionLvl41((PExpressionLvl41) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
