/* This file was generated by SableCC (http://www.sablecc.org/). */

package cps450.oodle.node;

import cps450.oodle.analysis.*;

@SuppressWarnings("nls")
public final class AEqExpr2 extends PExpr2
{
    private PExpr3 _starts_;
    private TOpEq _opEq_;
    private PExpr3 _ends_;

    public AEqExpr2()
    {
        // Constructor
    }

    public AEqExpr2(
        @SuppressWarnings("hiding") PExpr3 _starts_,
        @SuppressWarnings("hiding") TOpEq _opEq_,
        @SuppressWarnings("hiding") PExpr3 _ends_)
    {
        // Constructor
        setStarts(_starts_);

        setOpEq(_opEq_);

        setEnds(_ends_);

    }

    @Override
    public Object clone()
    {
        return new AEqExpr2(
            cloneNode(this._starts_),
            cloneNode(this._opEq_),
            cloneNode(this._ends_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEqExpr2(this);
    }

    public PExpr3 getStarts()
    {
        return this._starts_;
    }

    public void setStarts(PExpr3 node)
    {
        if(this._starts_ != null)
        {
            this._starts_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._starts_ = node;
    }

    public TOpEq getOpEq()
    {
        return this._opEq_;
    }

    public void setOpEq(TOpEq node)
    {
        if(this._opEq_ != null)
        {
            this._opEq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opEq_ = node;
    }

    public PExpr3 getEnds()
    {
        return this._ends_;
    }

    public void setEnds(PExpr3 node)
    {
        if(this._ends_ != null)
        {
            this._ends_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ends_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._starts_)
            + toString(this._opEq_)
            + toString(this._ends_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._starts_ == child)
        {
            this._starts_ = null;
            return;
        }

        if(this._opEq_ == child)
        {
            this._opEq_ = null;
            return;
        }

        if(this._ends_ == child)
        {
            this._ends_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._starts_ == oldChild)
        {
            setStarts((PExpr3) newChild);
            return;
        }

        if(this._opEq_ == oldChild)
        {
            setOpEq((TOpEq) newChild);
            return;
        }

        if(this._ends_ == oldChild)
        {
            setEnds((PExpr3) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
