/* This file was generated by SableCC (http://www.sablecc.org/). */

package cps450.oodle.node;

import cps450.oodle.analysis.*;

@SuppressWarnings("nls")
public final class AGtEqExpr2 extends PExpr2
{
    private PExpr3 _starts_;
    private TOpGteq _opGteq_;
    private PExpr3 _ends_;

    public AGtEqExpr2()
    {
        // Constructor
    }

    public AGtEqExpr2(
        @SuppressWarnings("hiding") PExpr3 _starts_,
        @SuppressWarnings("hiding") TOpGteq _opGteq_,
        @SuppressWarnings("hiding") PExpr3 _ends_)
    {
        // Constructor
        setStarts(_starts_);

        setOpGteq(_opGteq_);

        setEnds(_ends_);

    }

    @Override
    public Object clone()
    {
        return new AGtEqExpr2(
            cloneNode(this._starts_),
            cloneNode(this._opGteq_),
            cloneNode(this._ends_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGtEqExpr2(this);
    }

    public PExpr3 getStarts()
    {
        return this._starts_;
    }

    public void setStarts(PExpr3 node)
    {
        if(this._starts_ != null)
        {
            this._starts_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._starts_ = node;
    }

    public TOpGteq getOpGteq()
    {
        return this._opGteq_;
    }

    public void setOpGteq(TOpGteq node)
    {
        if(this._opGteq_ != null)
        {
            this._opGteq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opGteq_ = node;
    }

    public PExpr3 getEnds()
    {
        return this._ends_;
    }

    public void setEnds(PExpr3 node)
    {
        if(this._ends_ != null)
        {
            this._ends_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ends_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._starts_)
            + toString(this._opGteq_)
            + toString(this._ends_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._starts_ == child)
        {
            this._starts_ = null;
            return;
        }

        if(this._opGteq_ == child)
        {
            this._opGteq_ = null;
            return;
        }

        if(this._ends_ == child)
        {
            this._ends_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._starts_ == oldChild)
        {
            setStarts((PExpr3) newChild);
            return;
        }

        if(this._opGteq_ == oldChild)
        {
            setOpGteq((TOpGteq) newChild);
            return;
        }

        if(this._ends_ == oldChild)
        {
            setEnds((PExpr3) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
