/* This file was generated by SableCC (http://www.sablecc.org/). */

package cps450.oodle.node;

import java.util.*;
import cps450.oodle.analysis.*;

@SuppressWarnings("nls")
public final class ALoopStatement extends PStatement
{
    private TLoop _openloop_;
    private TWhile _while_;
    private PExpression _expression_;
    private final LinkedList<TCr> _cr_ = new LinkedList<TCr>();
    private PStatementList _statementList_;
    private TEnd _end_;
    private TLoop _closeloop_;

    public ALoopStatement()
    {
        // Constructor
    }

    public ALoopStatement(
        @SuppressWarnings("hiding") TLoop _openloop_,
        @SuppressWarnings("hiding") TWhile _while_,
        @SuppressWarnings("hiding") PExpression _expression_,
        @SuppressWarnings("hiding") List<?> _cr_,
        @SuppressWarnings("hiding") PStatementList _statementList_,
        @SuppressWarnings("hiding") TEnd _end_,
        @SuppressWarnings("hiding") TLoop _closeloop_)
    {
        // Constructor
        setOpenloop(_openloop_);

        setWhile(_while_);

        setExpression(_expression_);

        setCr(_cr_);

        setStatementList(_statementList_);

        setEnd(_end_);

        setCloseloop(_closeloop_);

    }

    @Override
    public Object clone()
    {
        return new ALoopStatement(
            cloneNode(this._openloop_),
            cloneNode(this._while_),
            cloneNode(this._expression_),
            cloneList(this._cr_),
            cloneNode(this._statementList_),
            cloneNode(this._end_),
            cloneNode(this._closeloop_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALoopStatement(this);
    }

    public TLoop getOpenloop()
    {
        return this._openloop_;
    }

    public void setOpenloop(TLoop node)
    {
        if(this._openloop_ != null)
        {
            this._openloop_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._openloop_ = node;
    }

    public TWhile getWhile()
    {
        return this._while_;
    }

    public void setWhile(TWhile node)
    {
        if(this._while_ != null)
        {
            this._while_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._while_ = node;
    }

    public PExpression getExpression()
    {
        return this._expression_;
    }

    public void setExpression(PExpression node)
    {
        if(this._expression_ != null)
        {
            this._expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression_ = node;
    }

    public LinkedList<TCr> getCr()
    {
        return this._cr_;
    }

    public void setCr(List<?> list)
    {
        for(TCr e : this._cr_)
        {
            e.parent(null);
        }
        this._cr_.clear();

        for(Object obj_e : list)
        {
            TCr e = (TCr) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._cr_.add(e);
        }
    }

    public PStatementList getStatementList()
    {
        return this._statementList_;
    }

    public void setStatementList(PStatementList node)
    {
        if(this._statementList_ != null)
        {
            this._statementList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._statementList_ = node;
    }

    public TEnd getEnd()
    {
        return this._end_;
    }

    public void setEnd(TEnd node)
    {
        if(this._end_ != null)
        {
            this._end_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._end_ = node;
    }

    public TLoop getCloseloop()
    {
        return this._closeloop_;
    }

    public void setCloseloop(TLoop node)
    {
        if(this._closeloop_ != null)
        {
            this._closeloop_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._closeloop_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._openloop_)
            + toString(this._while_)
            + toString(this._expression_)
            + toString(this._cr_)
            + toString(this._statementList_)
            + toString(this._end_)
            + toString(this._closeloop_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._openloop_ == child)
        {
            this._openloop_ = null;
            return;
        }

        if(this._while_ == child)
        {
            this._while_ = null;
            return;
        }

        if(this._expression_ == child)
        {
            this._expression_ = null;
            return;
        }

        if(this._cr_.remove(child))
        {
            return;
        }

        if(this._statementList_ == child)
        {
            this._statementList_ = null;
            return;
        }

        if(this._end_ == child)
        {
            this._end_ = null;
            return;
        }

        if(this._closeloop_ == child)
        {
            this._closeloop_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._openloop_ == oldChild)
        {
            setOpenloop((TLoop) newChild);
            return;
        }

        if(this._while_ == oldChild)
        {
            setWhile((TWhile) newChild);
            return;
        }

        if(this._expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        for(ListIterator<TCr> i = this._cr_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((TCr) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._statementList_ == oldChild)
        {
            setStatementList((PStatementList) newChild);
            return;
        }

        if(this._end_ == oldChild)
        {
            setEnd((TEnd) newChild);
            return;
        }

        if(this._closeloop_ == oldChild)
        {
            setCloseloop((TLoop) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
