/* This file was generated by SableCC (http://www.sablecc.org/). */

package cps450.oodle.node;

import cps450.oodle.analysis.*;

@SuppressWarnings("nls")
public final class ALtExpressionLvl4 extends PExpressionLvl4
{
    private PExpressionLvl4 _expressionLvl4_;
    private TLessThan _lessThan_;
    private PExpressionLvl41 _expressionLvl41_;

    public ALtExpressionLvl4()
    {
        // Constructor
    }

    public ALtExpressionLvl4(
        @SuppressWarnings("hiding") PExpressionLvl4 _expressionLvl4_,
        @SuppressWarnings("hiding") TLessThan _lessThan_,
        @SuppressWarnings("hiding") PExpressionLvl41 _expressionLvl41_)
    {
        // Constructor
        setExpressionLvl4(_expressionLvl4_);

        setLessThan(_lessThan_);

        setExpressionLvl41(_expressionLvl41_);

    }

    @Override
    public Object clone()
    {
        return new ALtExpressionLvl4(
            cloneNode(this._expressionLvl4_),
            cloneNode(this._lessThan_),
            cloneNode(this._expressionLvl41_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALtExpressionLvl4(this);
    }

    public PExpressionLvl4 getExpressionLvl4()
    {
        return this._expressionLvl4_;
    }

    public void setExpressionLvl4(PExpressionLvl4 node)
    {
        if(this._expressionLvl4_ != null)
        {
            this._expressionLvl4_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressionLvl4_ = node;
    }

    public TLessThan getLessThan()
    {
        return this._lessThan_;
    }

    public void setLessThan(TLessThan node)
    {
        if(this._lessThan_ != null)
        {
            this._lessThan_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lessThan_ = node;
    }

    public PExpressionLvl41 getExpressionLvl41()
    {
        return this._expressionLvl41_;
    }

    public void setExpressionLvl41(PExpressionLvl41 node)
    {
        if(this._expressionLvl41_ != null)
        {
            this._expressionLvl41_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressionLvl41_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expressionLvl4_)
            + toString(this._lessThan_)
            + toString(this._expressionLvl41_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expressionLvl4_ == child)
        {
            this._expressionLvl4_ = null;
            return;
        }

        if(this._lessThan_ == child)
        {
            this._lessThan_ = null;
            return;
        }

        if(this._expressionLvl41_ == child)
        {
            this._expressionLvl41_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expressionLvl4_ == oldChild)
        {
            setExpressionLvl4((PExpressionLvl4) newChild);
            return;
        }

        if(this._lessThan_ == oldChild)
        {
            setLessThan((TLessThan) newChild);
            return;
        }

        if(this._expressionLvl41_ == oldChild)
        {
            setExpressionLvl41((PExpressionLvl41) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
