/* This file was generated by SableCC (http://www.sablecc.org/). */

package cps450.oodle.node;

import java.util.*;
import cps450.oodle.analysis.*;

@SuppressWarnings("nls")
public final class ANewlines extends PNewlines
{
    private final LinkedList<TEmptyLine> _emptyLine_ = new LinkedList<TEmptyLine>();

    public ANewlines()
    {
        // Constructor
    }

    public ANewlines(
        @SuppressWarnings("hiding") List<?> _emptyLine_)
    {
        // Constructor
        setEmptyLine(_emptyLine_);

    }

    @Override
    public Object clone()
    {
        return new ANewlines(
            cloneList(this._emptyLine_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANewlines(this);
    }

    public LinkedList<TEmptyLine> getEmptyLine()
    {
        return this._emptyLine_;
    }

    public void setEmptyLine(List<?> list)
    {
        for(TEmptyLine e : this._emptyLine_)
        {
            e.parent(null);
        }
        this._emptyLine_.clear();

        for(Object obj_e : list)
        {
            TEmptyLine e = (TEmptyLine) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._emptyLine_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._emptyLine_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._emptyLine_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<TEmptyLine> i = this._emptyLine_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((TEmptyLine) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
