/* This file was generated by SableCC (http://www.sablecc.org/). */

package cps450.oodle.node;

import cps450.oodle.analysis.*;

@SuppressWarnings("nls")
public final class APassExpressionLvl4 extends PExpressionLvl4
{
    private PExpressionLvl41 _expressionLvl41_;

    public APassExpressionLvl4()
    {
        // Constructor
    }

    public APassExpressionLvl4(
        @SuppressWarnings("hiding") PExpressionLvl41 _expressionLvl41_)
    {
        // Constructor
        setExpressionLvl41(_expressionLvl41_);

    }

    @Override
    public Object clone()
    {
        return new APassExpressionLvl4(
            cloneNode(this._expressionLvl41_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPassExpressionLvl4(this);
    }

    public PExpressionLvl41 getExpressionLvl41()
    {
        return this._expressionLvl41_;
    }

    public void setExpressionLvl41(PExpressionLvl41 node)
    {
        if(this._expressionLvl41_ != null)
        {
            this._expressionLvl41_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressionLvl41_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expressionLvl41_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expressionLvl41_ == child)
        {
            this._expressionLvl41_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expressionLvl41_ == oldChild)
        {
            setExpressionLvl41((PExpressionLvl41) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
