/* This file was generated by SableCC (http://www.sablecc.org/). */

package cps450.oodle.node;

import cps450.oodle.analysis.*;

@SuppressWarnings("nls")
public final class APosExpr6 extends PExpr6
{
    private TOpPlus _opPlus_;
    private PExpr9 _e_;

    public APosExpr6()
    {
        // Constructor
    }

    public APosExpr6(
        @SuppressWarnings("hiding") TOpPlus _opPlus_,
        @SuppressWarnings("hiding") PExpr9 _e_)
    {
        // Constructor
        setOpPlus(_opPlus_);

        setE(_e_);

    }

    @Override
    public Object clone()
    {
        return new APosExpr6(
            cloneNode(this._opPlus_),
            cloneNode(this._e_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPosExpr6(this);
    }

    public TOpPlus getOpPlus()
    {
        return this._opPlus_;
    }

    public void setOpPlus(TOpPlus node)
    {
        if(this._opPlus_ != null)
        {
            this._opPlus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opPlus_ = node;
    }

    public PExpr9 getE()
    {
        return this._e_;
    }

    public void setE(PExpr9 node)
    {
        if(this._e_ != null)
        {
            this._e_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._e_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._opPlus_)
            + toString(this._e_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._opPlus_ == child)
        {
            this._opPlus_ = null;
            return;
        }

        if(this._e_ == child)
        {
            this._e_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._opPlus_ == oldChild)
        {
            setOpPlus((TOpPlus) newChild);
            return;
        }

        if(this._e_ == oldChild)
        {
            setE((PExpr9) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
