/* This file was generated by SableCC (http://www.sablecc.org/). */

package cps450.oodle.node;

import java.util.*;
import cps450.oodle.analysis.*;

@SuppressWarnings("nls")
public final class AStatementList extends PStatementList
{
    private final LinkedList<PStatementCr> _statementCr_ = new LinkedList<PStatementCr>();

    public AStatementList()
    {
        // Constructor
    }

    public AStatementList(
        @SuppressWarnings("hiding") List<?> _statementCr_)
    {
        // Constructor
        setStatementCr(_statementCr_);

    }

    @Override
    public Object clone()
    {
        return new AStatementList(
            cloneList(this._statementCr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStatementList(this);
    }

    public LinkedList<PStatementCr> getStatementCr()
    {
        return this._statementCr_;
    }

    public void setStatementCr(List<?> list)
    {
        for(PStatementCr e : this._statementCr_)
        {
            e.parent(null);
        }
        this._statementCr_.clear();

        for(Object obj_e : list)
        {
            PStatementCr e = (PStatementCr) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._statementCr_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._statementCr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._statementCr_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PStatementCr> i = this._statementCr_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PStatementCr) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
