/* This file was generated by SableCC (http://www.sablecc.org/). */

package cps450.oodle.node;

import cps450.oodle.analysis.*;

@SuppressWarnings("nls")
public final class ASubExpr4 extends PExpr4
{
    private PExpr4 _starts_;
    private TOpMinus _opMinus_;
    private PExpr5 _ends_;

    public ASubExpr4()
    {
        // Constructor
    }

    public ASubExpr4(
        @SuppressWarnings("hiding") PExpr4 _starts_,
        @SuppressWarnings("hiding") TOpMinus _opMinus_,
        @SuppressWarnings("hiding") PExpr5 _ends_)
    {
        // Constructor
        setStarts(_starts_);

        setOpMinus(_opMinus_);

        setEnds(_ends_);

    }

    @Override
    public Object clone()
    {
        return new ASubExpr4(
            cloneNode(this._starts_),
            cloneNode(this._opMinus_),
            cloneNode(this._ends_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASubExpr4(this);
    }

    public PExpr4 getStarts()
    {
        return this._starts_;
    }

    public void setStarts(PExpr4 node)
    {
        if(this._starts_ != null)
        {
            this._starts_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._starts_ = node;
    }

    public TOpMinus getOpMinus()
    {
        return this._opMinus_;
    }

    public void setOpMinus(TOpMinus node)
    {
        if(this._opMinus_ != null)
        {
            this._opMinus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opMinus_ = node;
    }

    public PExpr5 getEnds()
    {
        return this._ends_;
    }

    public void setEnds(PExpr5 node)
    {
        if(this._ends_ != null)
        {
            this._ends_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ends_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._starts_)
            + toString(this._opMinus_)
            + toString(this._ends_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._starts_ == child)
        {
            this._starts_ = null;
            return;
        }

        if(this._opMinus_ == child)
        {
            this._opMinus_ = null;
            return;
        }

        if(this._ends_ == child)
        {
            this._ends_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._starts_ == oldChild)
        {
            setStarts((PExpr4) newChild);
            return;
        }

        if(this._opMinus_ == oldChild)
        {
            setOpMinus((TOpMinus) newChild);
            return;
        }

        if(this._ends_ == oldChild)
        {
            setEnds((PExpr5) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
