/* This file was generated by SableCC (http://www.sablecc.org/). */

package cps450.oodle.node;

import java.util.*;
import cps450.oodle.analysis.*;

@SuppressWarnings("nls")
public final class AVariableDefinition extends PVariableDefinition
{
    private TIdentifier _identifier_;
    private PColonTypeProduction _colonTypeProduction_;
    private PEqualsExpression _equalsExpression_;
    private final LinkedList<TCr> _cr_ = new LinkedList<TCr>();

    public AVariableDefinition()
    {
        // Constructor
    }

    public AVariableDefinition(
        @SuppressWarnings("hiding") TIdentifier _identifier_,
        @SuppressWarnings("hiding") PColonTypeProduction _colonTypeProduction_,
        @SuppressWarnings("hiding") PEqualsExpression _equalsExpression_,
        @SuppressWarnings("hiding") List<?> _cr_)
    {
        // Constructor
        setIdentifier(_identifier_);

        setColonTypeProduction(_colonTypeProduction_);

        setEqualsExpression(_equalsExpression_);

        setCr(_cr_);

    }

    @Override
    public Object clone()
    {
        return new AVariableDefinition(
            cloneNode(this._identifier_),
            cloneNode(this._colonTypeProduction_),
            cloneNode(this._equalsExpression_),
            cloneList(this._cr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVariableDefinition(this);
    }

    public TIdentifier getIdentifier()
    {
        return this._identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(this._identifier_ != null)
        {
            this._identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identifier_ = node;
    }

    public PColonTypeProduction getColonTypeProduction()
    {
        return this._colonTypeProduction_;
    }

    public void setColonTypeProduction(PColonTypeProduction node)
    {
        if(this._colonTypeProduction_ != null)
        {
            this._colonTypeProduction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._colonTypeProduction_ = node;
    }

    public PEqualsExpression getEqualsExpression()
    {
        return this._equalsExpression_;
    }

    public void setEqualsExpression(PEqualsExpression node)
    {
        if(this._equalsExpression_ != null)
        {
            this._equalsExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._equalsExpression_ = node;
    }

    public LinkedList<TCr> getCr()
    {
        return this._cr_;
    }

    public void setCr(List<?> list)
    {
        for(TCr e : this._cr_)
        {
            e.parent(null);
        }
        this._cr_.clear();

        for(Object obj_e : list)
        {
            TCr e = (TCr) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._cr_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._identifier_)
            + toString(this._colonTypeProduction_)
            + toString(this._equalsExpression_)
            + toString(this._cr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._identifier_ == child)
        {
            this._identifier_ = null;
            return;
        }

        if(this._colonTypeProduction_ == child)
        {
            this._colonTypeProduction_ = null;
            return;
        }

        if(this._equalsExpression_ == child)
        {
            this._equalsExpression_ = null;
            return;
        }

        if(this._cr_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        if(this._colonTypeProduction_ == oldChild)
        {
            setColonTypeProduction((PColonTypeProduction) newChild);
            return;
        }

        if(this._equalsExpression_ == oldChild)
        {
            setEqualsExpression((PEqualsExpression) newChild);
            return;
        }

        for(ListIterator<TCr> i = this._cr_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((TCr) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
